[tool.poetry]
name = "streamlit_recev"
version = "0.1.0"
description = "A Streamlit app for receivables management"
authors = ["Your Name <your.email@example.com>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
